import {
Typography,
Box
} from "@mui/material";

export default function ReportFooter({pipeline}){

return(

<Box mt={4} mb={3}>

<Typography
variant="body2"
color="text.secondary"
>

Generated by Quantum AI Cancer Platform

Pipeline Version

{pipeline.metadata.pipeline_version}

</Typography>

</Box>

)

}